@extends('layouts.master')
@section('title', 'Laporan Neraca')
@section('container')
<section class="content-header"><h1>Laporan Neraca <small>Per {{ $report['as_of_date'] }}</small></h1></section>
<section class="content"><div class="box box-primary">
    <div class="box-header with-border"><form class="form-inline"><label>Per tanggal</label> <input type="date" name="as_of_date" class="form-control" value="{{ $report['as_of_date'] }}"> <button class="btn btn-default">Tampilkan</button> <a class="btn btn-success" href="{{ route('accounting.balance-sheet.export', ['as_of_date' => $report['as_of_date']]) }}"><i class="fa fa-file-excel-o"></i> XLSX</a></form></div>
    <div class="box-body"><div class="row"><div class="col-md-6"><h4>ASET</h4><table class="table table-bordered"><thead><tr><th>Kode</th><th>Akun</th><th class="text-right">Saldo</th></tr></thead><tbody>@forelse($report['assets'] as $row)<tr><td>{{ $row['account']->code }}</td><td>{{ $row['account']->name }}</td><td class="text-right">{{ number_format($row['balance'], 2, ',', '.') }}</td></tr>@empty<tr><td colspan="3">Belum ada aset.</td></tr>@endforelse</tbody><tfoot><tr><th colspan="2">Jumlah Aset</th><th class="text-right">{{ number_format($report['total_assets'], 2, ',', '.') }}</th></tr></tfoot></table></div><div class="col-md-6"><h4>LIABILITAS &amp; EKUITAS</h4><table class="table table-bordered"><thead><tr><th>Kode</th><th>Akun</th><th class="text-right">Saldo</th></tr></thead><tbody>@foreach($report['liabilities']->concat($report['equity']) as $row)<tr><td>{{ $row['account']->code }}</td><td>{{ $row['account']->name }}</td><td class="text-right">{{ number_format($row['balance'], 2, ',', '.') }}</td></tr>@endforeach<tr><td>-</td><td>Laba Tahun Berjalan</td><td class="text-right">{{ number_format($report['net_income'], 2, ',', '.') }}</td></tr></tbody><tfoot><tr><th colspan="2">Jumlah Liabilitas &amp; Ekuitas</th><th class="text-right">{{ number_format($report['total_liabilities'] + $report['total_equity'], 2, ',', '.') }}</th></tr></tfoot></table></div></div><div class="alert {{ abs($report['total_assets'] - ($report['total_liabilities'] + $report['total_equity'])) < 0.01 ? 'alert-success' : 'alert-warning' }}">Selisih neraca: <strong>{{ number_format($report['total_assets'] - ($report['total_liabilities'] + $report['total_equity']), 2, ',', '.') }}</strong></div></div>
</div></section>
@endsection
