@extends('layouts.master')
@section('title', 'Laporan Laba Rugi')
@section('container')
<section class="content-header"><h1>Laporan Laba Rugi <small>Periode {{ $report['start_date'] }} s/d {{ $report['end_date'] }}</small></h1></section>
<section class="content"><div class="box box-primary">
    <div class="box-header with-border"><form class="form-inline"><input type="date" name="date_from" class="form-control" value="{{ $report['start_date'] }}"> s/d <input type="date" name="date_to" class="form-control" value="{{ $report['end_date'] }}"> <button class="btn btn-default">Tampilkan</button> <a class="btn btn-success" href="{{ route('accounting.profit-loss.export', ['date_from' => $report['start_date'], 'date_to' => $report['end_date']]) }}"><i class="fa fa-file-excel-o"></i> XLSX</a></form></div>
    <div class="box-body"><table class="table table-bordered"><thead><tr><th>Bagian</th><th>Kode</th><th>Akun</th><th class="text-right">Nilai</th></tr></thead><tbody>@forelse($report['rows'] as $row)<tr><td>{{ $row['section'] }}</td><td>{{ $row['account']->code }}</td><td>{{ $row['account']->name }}</td><td class="text-right">{{ number_format($row['amount'], 2, ',', '.') }}</td></tr>@empty<tr><td colspan="4" class="text-center">Belum ada transaksi pendapatan/beban.</td></tr>@endforelse</tbody><tfoot><tr><th colspan="3" class="text-right">Total Pendapatan</th><th class="text-right">{{ number_format($report['income'], 2, ',', '.') }}</th></tr><tr><th colspan="3" class="text-right">Total Beban</th><th class="text-right">{{ number_format($report['expense'], 2, ',', '.') }}</th></tr><tr class="{{ $report['net_income'] >= 0 ? 'success' : 'danger' }}"><th colspan="3" class="text-right">{{ $report['net_income'] >= 0 ? 'LABA BERSIH' : 'RUGI BERSIH' }}</th><th class="text-right">{{ number_format(abs($report['net_income']), 2, ',', '.') }}</th></tr></tfoot></table></div>
</div></section>
@endsection
